services:
  fastapi-prod:
    image: fastapi-custom
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "8011:8011"
    volumes:
      - ./app:/app/app
    env_file:
      - ./docker/prod/.env
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8011"
    restart: unless-stopped
    networks:
      - app-network

  fastapi-preprod:
    image: fastapi-custom
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "8010:8010"
    volumes:
      - ./app:/app/app
    env_file:
      - ./docker/preprod/.env
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8010 --reload --reload-dir /app/app"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
