import polars as pl

schema_drivers = {
    'driver_id': pl.Int64,
    'worker_id': pl.Int64,
    'driver_name': pl.String,
    'active_flag': pl.Int64,
    'driver_code': pl.Int64,
    'client_group': pl.Int64,
    'group_name': pl.String,
    'parent_group': pl.Int64,
    'parent_group_name': pl.String,
    'driver_cell_phone': pl.Int64,
    'driver_main_vehicle_id': pl.Int64,
    'driver_main_vehicle_license_number': pl.Int64,
    'customer_contact_person': pl.String,
    'contact_person_phone_number': pl.String,
    'driver_email': pl.String,
    'last_event_id': pl.Int64,
    'last_event_time': pl.String,
    'last_event_type': pl.Int64,
    'last_event_type_desc': pl.String,
    'last_event_vehicle': pl.Int64,
    'last_event_licence_number': pl.Int64,
    'last_event_location': pl.String,
    'last_event_latitude': pl.Float64,
    'last_event_longitude': pl.Float64,
    'last_event_direction': pl.Int64,
    'fecha_extraccion': pl.String,
    'year': pl.Int64,
    'month': pl.Int64,
}


schema_trff_events = {
    '_hoodie_commit_time': pl.Int64,
    '_hoodie_commit_seqno': pl.String,
    '_hoodie_record_key': pl.String,
    '_hoodie_partition_path': pl.String,
    '_hoodie_file_name': pl.String,
    'trip_id': pl.Int64,
    'event_id': pl.Int64,
    'vehicle_id': pl.Int64,
    'license_number': pl.Int64,
    'time': pl.String,
    'event_type_id': pl.Int64,
    'event_type_description': pl.String,
    'event_category': pl.Int64,
    'event_category_description': pl.String,
    'latitude': pl.Float64,
    'longitude': pl.Float64,
    'speed': pl.Float64,
    'direction': pl.Float64,
    'driver_id': pl.Int64,
    'driver_name': pl.String,
    'driver_code': pl.Int64,
    'worker_id': pl.Int64,
    'time_cdmx': pl.String,
    'fecha_ultima_actualizacion': pl.String,
    'part_year': pl.Int64,
    'part_mont': pl.Int64,
    'part_day': pl.Int64,
}

rename_trff_events = {
    'license_number': 'IdVehiculo',
    'event_type_description': 'evento',
}

schema_flota = {
    'vehicle_id': pl.Int64,
    'entity_id': pl.Int64,
    'entity_name': pl.String,
    'eco': pl.Int64,
    'serial_number': pl.String,
    'status_id': pl.Int64,
    'status_name': pl.String,
    'usage_id': pl.Int64,
    'usage_name': pl.String,
    'manufacturer_name': pl.String,
    'model_name': pl.String,
    'vehicle_year': pl.Int64,
    'vehicle_type_name': pl.String,
    'description': pl.String,
    'fuel_type': pl.String,
    'plates': pl.String,
    'federal_plantes': pl.String,
    'parking_lot': pl.String,
    'passengers': pl.Int64,
    'engine_number': pl.String,
    'last_odometer_fuel_ticket': pl.Float64,
    'status_group_id': pl.Int64,
    'status_group_name': pl.String,
    'last_communication_time': pl.String,
    'origin_id': pl.Int64,
    'origin_name':pl.String,
    'fecha': pl.Date,
    'fecha_cdmx': pl.Date,
}

rename_flota = {
    'entity_name':'Unidad de negocio',
    'vehicle_id':'IdVehiculo',
    'vehicle_type_name':'Tipo vehiculo',
    'status_group_name':'Gpo. estatus',
    'usage_name':'Uso',
    'status_name':'Estatus',
    'fuel_type':'Combustible',
    'description':'Descripcion',
    'serial_number':'vin',
    'origin_name':'Origen',
    'manufacturer_name':'Marca',
    'model_name':'Modelo',
    'passengers':'asientos',
    'vehicle_year':'ao'
}

schema_vdt = {
    '_hoodie_commit_time' : pl.Int64,
    '_hoodie_commit_seqno': pl.String,
    '_hoodie_record_key': pl.String,
    '_hoodie_partition_path': pl.String,
    '_hoodie_file_name': pl.String,
    'vehicle_id': pl.Int64,
    'licence_number': pl.Int64,
    'driver_id': pl.Int64,
    'start_time': pl.Datetime,
    'end_time': pl.Datetime,
    'start_location': pl.String,
    'end_location': pl.String,
    'drive_id': pl.Int64,
    'distance': pl.Float64,
    'start_latitude': pl.Float64,
    'start_longitude': pl.Float64,
    'end_latitude': pl.Float64,
    'end_longitude': pl.Float64,
    'start_time_cdmx': pl.Datetime,
    'end_time_cdmx': pl.Datetime,
    'fecha_ultima_actualizacion': pl.String,
    'part_year': pl.Int64,
    'part_month': pl.Int64
}

# schema_vf = {
#     'id': pl.Int64,	
#     'id_servicio': pl.String,
#     'business_unit': pl.String,
#     'des': pl.String,
#     'tipo_de_viaje': pl.String,
#     'id_ruta': pl.Int64,
#     'desc_adicional': pl.String,
#     'car': pl.Int64,
#     'status': pl.Int64,
#     'shift': pl.String,
#     'group': pl.String,
#     'start_date': pl.String,
#     'start_time': pl.String,
#     'end_date': pl.String,
#     'end_time': pl.String,
#     'start_eta': pl.String,
#     'end_eta': pl.String,
#     'start_status': pl.String,
#     'end_status': pl.String,
#     'record_quality': pl.Int64,
#     'km_cotizado': pl.Float64,
#     'km_promedio': pl.Float64,
#     'km_calc': pl.Float64,
#     'km_calc_+_vac': pl.Float64,
#     'km_vac_inicial': pl.Float64,
#     'km_vac_final': pl.Float64,
#     'driver': pl.String,
#     'worker_id': pl.Int64,
#     'operador': pl.String,
#     'no_de_nomina': pl.Int64,
#     'usuario': pl.String,
#     'fecha_de_creación__tiempo_de_servidor': pl.String,
#     'momento': pl.String,
#     'sem_via': pl.Int64,
#     'sol_viaje': pl.String,
#     'diagnostico_viaje': pl.String,
#     '$_viaje': pl.Float64,
#     '$_viaje_fijo': pl.Float64,
#     'tipo_de_facturación': pl.String,
#     'periodo_de_facturación': pl.String,
#     'fecha_de_creación__tiempo_de_unidad_de_negocios_#1': pl.String,
#     'aforo': pl.Int64,
#     'start_datetime': pl.Datetime,
#     'end_datetime': pl.Datetime,
# }

schema_vf = {
    'id': pl.Int64,	
    'id_servicio': pl.String,
    'business_unit': pl.String,
    'des': pl.String,
    'tipo_de_viaje': pl.String,
    'id_ruta': pl.Int64,
    'desc_adicional': pl.String,
    'car': pl.Int64,
    'status': pl.Int64,
    'shift': pl.String,
    'group': pl.String,
    'start_date': pl.String,
    'start_time': pl.String,
    'end_date': pl.String,
    'end_time': pl.String,
    'start_eta': pl.String,
    'end_eta': pl.String,
    'start_status': pl.String,
    'end_status': pl.String,
    'record_quality': pl.Int64,
    'km_cotizado': pl.Float64,
    'km_promedio': pl.Float64,
    'km_calc': pl.Float64,
    'km_calc_+_vac': pl.Float64,
    'km_vac_inicial': pl.Float64,
    'km_vac_final': pl.Float64,
    'driver': pl.String,
    'worker_id': pl.Int64,
    'operador': pl.String,
    'no_de_nomina': pl.Int64,
    'usuario': pl.String,
    'fecha_creacion_tiempo_de_servidor': pl.String,  #  CORREGIDO
    'momento': pl.String,
    'sem_via': pl.Int64,
    'sol_viaje': pl.String,
    'diagnostico_viaje': pl.String,
    '$_viaje': pl.Float64,
    '$_viaje_fijo': pl.Float64,
    'tipo_de_facturación': pl.String,
    'periodo_de_facturación': pl.String,
    'fecha_creacion_tiempo_de_unidad_negocios': pl.String,  # CORREGIDO
    'aforo': pl.Int64,
    'start_datetime': pl.Datetime,
    'end_datetime': pl.Datetime,
}

schema_flota_trf = {
    '_hoodie_commit_time': pl.Int64,
    '_hoodie_commit_seqno': pl.String,
    '_hoodie_record_key': pl.Int64,
    '_hoodie_partition_path': pl.String,
    '_hoodie_file_name': pl.String,
    'vehicle_id': pl.Int64,
    'unit_id': pl.Int64,
    'group_id': pl.Int64,
    'group_name': pl.String,
    'client_id': pl.Int64,
    'client_name': pl.String,
    'unit_serial': pl.Int64,
    'license_nmbr': pl.Int64,
    'chassis_number': pl.String,
    'last_communication_time': pl.String,
    'last_position_time': pl.String,
    'latitude': pl.Float64,
    'longitude': pl.Float64,
    'speed': pl.Int64,
    'direction': pl.Int64,
    'status': pl.Int64,
    'last_event_time': pl.String,
    'last_event_type': pl.String,
    'current_driver': pl.Int64,
    'current_driver_number': pl.Int64,
    'driver_name': pl.String,
    'worker_id': pl.Int64,
    'current_drive': pl.Int64,
    'last_mileage': pl.Float64,
}

schema_flota_trf_h = {
    'vehicle_id': pl.Int64,
    'unit_id': pl.Int64,
    'group_id': pl.Int64,
    'group_name': pl.String,
    'client_id': pl.Int64,
    'client_name': pl.String,
    'unit_serial': pl.Int64,
    'license_nmbr': pl.String,
    'chassis_number': pl.String,
    'last_communication_time': pl.String,
    'last_position_time': pl.String,
    'latitude': pl.Float64,
    'longitude': pl.Float64,
    'speed': pl.Int64,
    'direction': pl.Int64,
    'status': pl.Int64,
    'last_event_time': pl.String,
    'last_event_type': pl.String,
    'current_driver': pl.Int64,
    'current_driver_number': pl.Int64,
    'driver_name': pl.String,
    'worker_id': pl.Int64,
    'current_drive': pl.Int64,
    'last_mileage': pl.Float64,
    'fecha_extraccion': pl.Date,
    'last_communication_time_cdmx': pl.String,
    'last_position_time_cdmx': pl.String,
    'last_event_time_cdmx': pl.String,
    'year': pl.Int64,
    'month': pl.Int64,
}

schema_cargas = {
    'id_plaza': pl.Int64,
    'plaza': pl.String,
    'fk_vehicle': pl.Int64,
    'eco': pl.Int64,
    'nombre_operador': pl.String,
    'id_operador': pl.Int64,
    'fuel_ticket_date': pl.String,
    'ticket_number': pl.Int64,
    'odometro_trafilog_sigo': pl.Float64,
    'odometro_trafilog_actual': pl.Float64,
    'km_recorridos_trafilog': pl.Float64,
    'previous_odometer': pl.Float64,
    'odometer': pl.Float64,
    'distance': pl.Float64,
    'dispatched_fuel': pl.Float64,
    'base_cost': pl.Float64,
    'fuel_consumption': pl.Float64,
    'authorized_fuel_consumption': pl.String,
    'fuel': pl.String,
    'entity_fuel_provider': pl.String,
    'user': pl.String,
    'precio_combustible': pl.Float64,
    'registry_date': pl.String,
}

rename_flota_trf = {
    'group_name': 'cliente_trf',
    'license_nmbr': 'IdVehiculo',
    'latitude': 'lat',
    'longitude': 'lon',
}

rename_flota_trf_h = {
    'group_name': 'cliente_trf',
    'license_nmbr': 'IdVehiculo',
    'last_position_time_cdmx': 'dt_last_pos',
    'last_communication_time_cdmx': 'dt_last_com',
    'latitude': 'lat',
    'longitude': 'lon',
    'group_name':'grupo',
    'client_name':'cliente',
}

rename_vdt = {
    'start_time_cdmx': 'ini_fh',
    'end_time_cdmx': 'fin_fh',
    'distance': 'kms',
    'licence_number': 'IdVehiculo',
}

rename_cargas = {
    'ticket_number':'folio',
    'fk_vehicle':'IdVehiculo',
    'fuel_ticket_date':'fecha_carga',
    'km_recorridos_trafilog': 'kms_carga_gps',
    'distance':'kms_carga',
    'fuel':'combustible',
    'dispatched_fuel':'litros',
    'plaza':'udn',
    'entity_fuel_provider':'proveedor',
    'user':'usuario',
    'nombre_operador': 'operador',
}

rename_vf = {
    'business_unit':'udn',
    'group':'cliente',
    'start_date':'fecha_ini',
}

